### ISSUE TITLE
Feature idea: Metadata navigator

### ISSUE THREAD

**Issue by aengelberg** [nathanmarz/specter#114]
A `META` navigator which can select the metadata map of an object with `meta` and also transform it with `with-meta`.

Examples:
```
;; set :x to 1 in all objects' metadata maps without touching other metadata keys
(setval [ALL META :x] 1 my-data)
;; turn all metadata keys into namespaced keys under my namespace
(transform [ALL META ALL FIRST] #(keyword "com.alex" (name %)) my-data)
```

**Comment by nathanmarz** [comment]
Good idea, I'd accept a pull request for this.

**Comment by aengelberg** [comment]
One design question is how to behave when navigating to the metadata of a non `IObj` structure. Some choices available:
- select doesn't navigate to anything. transform doesn't navigate to anything. (i.e. skips this structure in the traversal.)
- select navigates to nil. transform doesn't navigate to anything.
- select navigates to nil. transform navigates to nil and attempts to `with-meta` the result no matter what. it's on the user to be careful about attaching metadata when Clojure doesn't allow it.

Thoughts?

**Comment by nathanmarz** [comment]
I'm leaning towards the 3rd option. That will give an error if the object doesn't support metadata, which in my experience using metadata is what I would want. As a user you can always get the behavior of the 1st approach by doing `(comp-paths #(instance? IObj %) META)`.

This behavior would be inconsistent with FIRST/LAST which stop on empty sequences rather than giving an error. It's debatable but I'm not confident that was the right design decision.
