### ISSUE TITLE
Transforming a list leads to a lazyseq

### ISSUE THREAD

**Issue by marick** [nathanmarz/specter#126]
Via `AllTransformProtocol`, `(transform [... ALL ...] ... ...)` preserves the type of transformed structures. For example, `(transform [ALL] inc [1 2 3])` produces a `vector?`, and `(transform [ALL] inc (map dec [1 2 3]))` produces a lazy sequence. 

I notice that doesn't work for old-fashioned Lisp lists:

```
user=> (def result (transform [ALL] inc (list 1 2)))
user=> (type result)
clojure.lang.LazySeq
```

Intentional? (I, uncharitably, suspect clojurescript.) I could add another clause to the `extend-protocol` and make a pull request, but I'm not sure about testing clojurescript. (`lein cleantest`?)

**Comment by nathanmarz** [comment]
This is unfortunately intentional, as I just don't know any way to maintain order with only one pass while doing `ALL` over `PersistentList`. If you do `(into '() (map inc) '(1 2 3))` you get `(4 3 2)`.

The `LazySeq` that it returns is fully realized, and the reason Specter has used it as a substitute for `PersistentList` is because it's behavior is the same as `PersistentList` (e.g. with respect to `conj`). 

I haven't done a performance investigation into creating a realized `LazySeq` in one pass versus creating a `PersistentList` in two passes, so it's possible the latter is better.

**Comment by lvh** [comment]
FWIW, this just bit me. I'm using specter to transform expressions on a query lang. Unfortunately, the seq looks exactly  like a list (because it's fully realized, presumably).

**Comment by nathanmarz** [comment]
Can you elaborate on the problem this caused for you?

**Comment by lvh** [comment]
Sure! I'm writing some code that queries a tree of vecs and maps. For some simple queries, I have a simplified language that compiles down to specter. For example, it takes queries like `[:a :b _ :whatever]`, does the right thing with applying `keypath`, and replaces `_`  with `(sr/cond-path vector? sr/ALL map? sr/MAP-VALS)`.

This all worked fine until I added a parameter-taking navigator. In particular, people wanted to collect some data as this query walked down the tree, so, `collect-one`. Since I get this as data, the input is a `list`. I also use specter to rewrite the "simple" query language into a real specter query (it's specter all the way down).

I also support a more complex query language which is basically datalog with a preset set of rules for when a "simple" tree walk isn't good enough. Of course, that means I need to figure out which query it is in order to execute it. I use spec to do so. 

The spec looks like a typical data structure spec: elements are either `keyword?`, `string?`... or `list?`. This worked fine until I introduced a specter preprocessing step. Per usual specter rules, I was expecting it to keep lists as lists, but instead it produced a LazySeq, so suddenly that query failed spec, and figuring out why was a pain in the neck (because the fully realized lazyseq looks _just like_ an IPersistentList when passed to the printer).

**Comment by nathanmarz** [comment]
Thanks for the explanation. This is an unfortunate edge case in Specter, as I felt it was worth transforming to a different type since the behavior of the type is the same and the performance is better. `seq?` is a good function to use since lists and lazyseq's both return true for it while a vector returns false.
