### ISSUE TITLE
alternate for threading multiple transforms

### ISSUE THREAD

**Issue by JoePython1** [nathanmarz/specter#197]
Currently I thread lots of  transforms upon transforms like this and it is becoming really wordy.:

``` clojure
(->> (data)
       (transform [do re me f] func1)
       (transform [x y z] func2)
       (transform [v f hf] func3)
       (transform [v f hf] func4)
       (transform [v f hfd] func5)
        and so on ......))
```

Is there a way to abstract these navs and functions which have to transformed?

**Comment by nathanmarz** [comment]
There's `multi-transform` which you can use along with `terminal` and `terminal-val` to combine transforms which share part of their paths. This is also faster since it avoids multiple iterations / reconstructions for the shared portion of the path.

You could also easily make a `-transform>>` macro to avoid having to type `transform` over and over, e.g.:

```clojure
(-transform>>
  data
  ([do re me f] func1)
  ([x y z] func2)
  ...
  )     
```

Does that answer your question?

**Comment by JoePython1** [comment]
Thank you
