### ISSUE TITLE
lein codox produces an error if the source code contains s/END

### ISSUE THREAD

**Issue by luminusian** [nathanmarz/specter#212]
Adding the following code produces an error when running `lein codox` is run.

```
(s/setval s/END [:a] [])
```
```
clojure.lang.ExceptionInfo: Unable to resolve var: END in this context
```

**Comment by nathanmarz** [comment]
Codox works fine on Specter itself. If anything, this should be reported on Codox, not Specter.

**Comment by luminusian** [comment]
According to @weavejester,

>It's likely there's a problem in your codebase, as the error you're seeing is very probably from the Clojure compiler when it tries to evaluate the namespaces in your application.

The following codebase that reproduces the error only adds a little to boilerplate.

https://github.com/luminusian/specter-codox

**Comment by weavejester** [comment]
To be clear, that's when I assumed you were compiling a Clojure project, since you didn't specify otherwise.

The next step I think you should try is to compile the project normally and see if the error occurs, then try adding "codox" manually as a dependency, and see if it still compiles. If it breaks there might be some dependency mismatch.

**Comment by luminusian** [comment]
>compile the project normally and see if the error occurs

The error doesn't occur.

>Try adding "codox" manually as a dependency, and see if it still compiles.

It still compiles.

https://github.com/luminusian/specter-codox
