### ISSUE TITLE
Keep only what I want from a nested map

### ISSUE THREAD

**Issue by DjebbZ** [nathanmarz/specter#247]
Hi,

Given
``` clojure
(def initial {:a {:a1 1
                  :a2 2}
              :b {:b1 3
                  :b2 {:b21 1
                       :b22 {:b221 1
                             :b222 2}}}})
```
I want to keep only certain keys at several levels, not necessarily leaves. Kinda like tree shaking.

I want this 
``` clojure
(def wanted {:a {:a1 1}
             :b {:b2 {:b22 {:b221 1
                            :b222 2}}}})
```

To be precise, I don't necessarily know/want to specify the parts I want to remove. In this particular example, I want to keep the following paths :

``` clojure
[[:a :a1]
 [:b :b2 :b22]]
```

Is there a way in Specter to express this intent (`what-I-want-keep`)  ? I know I can express the opposite : `setval` to `NONE` `what-I-want-to-remove`.

**Comment by nathanmarz** [comment]
If you want to maintain the structure of the input, then the general pattern with Specter is `(setval <path> NONE data)`. `compact` can be used to propagate removals to newly empty substructures. Navigation can only instruct how to get somewhere and what to do on arrival, and since the operation you reference is removal, the navigation needs to be towards the elements to remove.

**Comment by DjebbZ** [comment]
This was my intuition. Thanks.
