### ISSUE TITLE
Find an element's parent?

### ISSUE THREAD

**Issue by nodename** [nathanmarz/specter#58]
I suspect the answer may resemble that in #57 . If so, I may be understanding that one a bit!

**Comment by nathanmarz** [comment]
There are many different answers depending on the specifics of your data structure. Can you give a specific example of what you're trying to do?

**Comment by nodename** [comment]
Sure. Nested maps like
`{:a nil
  :b {:ba {:baa nil}}}`

So gven `:baa` I'd want to get back `:ba` for example

**Comment by nathanmarz** [comment]
Once you navigate into a nested map, you can't navigate up. With Specter what you do instead is make use of the values collection feature to collect the values you need as you go. For example:

```clojure
(transform [ALL (collect-one :b) :a even?]
              +
              [{:a 1 :b 3} {:a 2 :b -10} {:a 4 :b 10}])
;; => [{:b 3, :a 1} {:b -10, :a -8} {:b 10, :a 14}]
```
 
Here, the value of :b is added into the value of :a (when the value for :a is even). Since the value for :b is inaccessible once the value for :a has been reached, it is collected before navigating into :a. The transform function receives as input the collected values followed by the value navigated to. 

collect works just like select, and collect-one works like select-one. Both collect and collect-one take in an arbitrary navigation path as input.

**Comment by nodename** [comment]
Hmm I don't think that addresses my case; maybe Specter isn't the right tool for this particular job
