### ISSUE TITLE
srange-like manipulation for arbitrarily nested structures

### ISSUE THREAD

**Issue by pmwhite** [nathanmarz/specter#80]
Here is my data structure.

    (this has lots (of ?&holes ?that (?are deeply ?nested) ?and stuff ?like (?that)))

Now, by using `(walker hole?)`, I can get all the symbols that start with a question mark. This is useful, but I also want to do something else. If the first symbol that starts with a question mark also has an ampersand (in this case, that condition is true), I want to expand it to two holes, the first of which does not have the ampersand. The final data will look like this

    (this has lots (of ?holes ?&holes ?that (?are deeply ?nested) ?and stuff ?like (?that)))

The first "hole" could be anywhere, so `walker` seems to be a good fit, but it doesn't seem to allow for this type of transformation. `srange` also seems to be related. Now, I think I could completely reimplement `walker` to allow for what I'm trying to do, but there is probably a better, and more idiomatic way. What's the right way to do this?

**Comment by nathanmarz** [comment]
This is a use case that's better handled by zippers. Just keep calling `next` until you find your "hole", and then call `insert-right`. The next release of Specter will have zippers integrated into Specter, though it's not currently integrated.

**Comment by nathanmarz** [comment]
You're lucky that you asked this particular question as I was finishing up the zipper integration :)

Here's sample code from the master branch that handles this use case:

```clojure
(use 'com.rpl.specter)
(use 'com.rpl.specter.macros)
(use 'com.rpl.specter.zipper)

(declarepath find [predfn])

(providepath find
  (if-path [NODE pred]
    STAY
    [NEXT (params-reset find)]
    ))

(defn number>=10 [n]
  (and (number? n) (>= n 10)))

(transform [VECTOR-ZIP (find number>=10) (collect-one NODE) INNER-RIGHT]
  (fn [v _]
    [(str v "!")])
  [1 [2 10 [4]] 12])
```

This code finds the first number >= 10 and inserts that number as a string with an exclamation point immediately after it. If it finds no such number, the structure is unchanged. As you can see here, the `find` navigator is parameterized with the predicate to match by, and so is completely generic.

**Comment by pmwhite** [comment]
Haha, that's awesome; thanks a lot. I noticed that you used `pred` in the `providepath` but `predfn` in the `declarepath`; is that a mistake?

**Comment by nathanmarz** [comment]
No, that code is correct. This is about as advanced as Specter usage gets, as `find` is a recursive parameterized path, so it might take a bit to wrap your head around it. Here's a quick explanation:

- `predfn` is just naming one of the parameters to the `find` path. The name is irrelevant to the execution, all Specter cares about at runtime is how many parameters `find` requires.
- `pred` is a filter navigator that takes in the filter function as a parameter. As you can see from the definition of `find`, its definition requires a single parameter total (for `pred`).
- Since it's recursive, `find` needs to call itself. But to make sense it needs to parameterize its invocation. So `params-reset` tells it to use the same parameters for the recursive navigation.
