### ISSUE TITLE
Question about a Select where certain 'key value' pairs need to be replaced with data from maps in another sequence.

### ISSUE THREAD

**Issue by ndroock1** [nathanmarz/specter#84]
Consider the following two hypothetical and over-simplified vectors of maps:
1. categories
[ {:id 1 :data {text: "Core / Mother" test: 51} :prev nil :par nil}
  {:id 2 :data {text: "Control / M" test: 51} :prev nil :par 1} ]
2 items
[ {:id 1 :data {text: "Agent 001" test: 0 } :prev nil :par nil :cats [ {:cid 1} {: cid 2} }
  etc.  ]
My question is how do I select all maps in items with replacing {:cid N } with all data from a category with {id N} ?

P.S.
Although I only just discovered it, I think that calling Specter the 'missing piece in Clojure(Script)' is a well chosen description for this amazing library. The available documentation: a short blog piece, a source file and a YouTube video containing a recorded Emacs session, in my opinion, is not in-sync with the magnitude of Specter as a product.

**Comment by nathanmarz** [comment]
Here's one way to do it:

```clojure
(transform [ALL :cats ALL (collect-one :cid)]
  (fn [id _]
    (select-one! [ALL (selected? :id #(= % id))]
      categories
      ))
  items
  )
```

If `categories` is large, you're probably better off storing it as a map from id -> data and doing direct lookups rather than scan and filter.

Glad that you appreciate the power of the library. Wish I had more time to write documentation, but my startup takes priority. Almost everything inside Specter emerged from use cases I needed to handle for my startup.

**Comment by ndroock1** [comment]
Thank you nathanmarz
